Development
tevaera-labs/edcon-poc pull request #1
Opened 2024-06-24 15:04 UTC by nikhiltevaera

2024-06-25 11:41 UTC, gauravl-tevaeralabs requested changes

2024-06-25 11:41 UTC, gauravl-tevaeralabs commented on README.md
> -The proof of concept for EDCON-24 App
Please POC outside as well so that as soon as someone loads the repo, they get to see the information on the repository.
We can brief on the purpose of creating this repo and also inform user to refer to respected README available in respected modules. for all readme make sure it's in capital letter.

2024-06-25 11:41 UTC, gauravl-tevaeralabs commented on backend/.env.template
> +PUBLIC_KEY=#{PUBLIC_KEY}#
If private key is available, we can get public key from private key itself (through wallet instance), no need to specify public key separately in .env

2024-06-25 11:41 UTC, gauravl-tevaeralabs commented on backend/.env.template
> +WALLET_PRIVATE_KEY=#{WALLET_PRIVATE_KEY}#   #edcon private key
what is the difference between PRIVATE_KEY & WALLET_PRIVATE_KEY?

2024-06-25 11:41 UTC, gauravl-tevaeralabs commented on backend/src/services/ExecuteTransaction.ts
> +  if (method === "transferFrom") {
this code (the entire IF condition with nested IF conditions) is not readable. Please try to divide it into separate methods for erc20, 721 & 1155 and try to optimize it.

2024-06-25 11:41 UTC, gauravl-tevaeralabs commented on backend/src/utils/chainRpcMap.ts
> +export const chainRpcMap:any = {
Create a file called constans or rename this file to constants, and try to move all hardcoded constants to the same file - so people can refer to constants for any addition or deletion.

2024-06-25 11:41 UTC, gauravl-tevaeralabs commented on frontend/.env.template
> +NEXT_PUBLIC_PRIVATE_KEY=#{NEXT_PUBLIC_PRIVATE_KEY}#
frontend should not have any private key

2024-06-25 11:41 UTC, gauravl-tevaeralabs commented on frontend/.env.template
> +NEXT_PUBLIC_PRIVATE_KEY=#{NEXT_PUBLIC_PRIVATE_KEY}#
as it would be exposed to the client

2024-06-25 11:46 UTC, nikhiltevaera commented on backend/.env.template
> +PUBLIC_KEY=#{PUBLIC_KEY}#
These public key private key are not a part of wallet,
its for encryption and decryption algorithms

2024-06-25 11:46 UTC, nikhiltevaera commented on backend/.env.template
> +WALLET_PRIVATE_KEY=#{WALLET_PRIVATE_KEY}#   #edcon private key
PRIVATE_KEY refers to the ecnryption private key ,this is different from the wallet private key

2024-06-26 12:53 UTC, gauravl-tevaeralabs approved these changes

2024-06-26 12:53 UTC, merged